### ISSUE TITLE
JS issues on client-side

### ISSUE THREAD

**Issue by marcobambini** [sqlitecloud/sqlitecloud-js#90]
JS works on the server-side (NodeJS) but not on the client-side.
If you try to `npm` and then `import`, several issues arise, even if the library should work.

**Comment by Gioee** [comment]
This was the error: **Module not found: Can’t resolve ‘tls’.**

The tls module is a Node module and should be ignored in client/web mode, and indeed webpack should do this:
https://github.com/sqlitecloud/sqlitecloud-js/blob/ee463e56f35a10b0c8576d7d915c98fdc969b216/webpack.config.js#L29

Since webpack does not set the tls module to false in browser mode, I've found that adding
```
"browser": {
 "tls": false
}
```
to the package.json file should have the same effect. However, after some tests, setting tls to false in package.json seems to work, unlike in webpack.
